# This file was generated by GoReleaser. DO NOT EDIT.
cask "kubefwd" do
  name "kubefwd"
  desc "Kubernetes bulk port forwarding utility."
  homepage "https://github.com/txn2/kubefwd"
  version "1.23.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kubefwd"
  depends_on formula: [
      "kubectl",
    ]

  on_macos do
    on_intel do
      url "https://github.com/txn2/kubefwd/releases/download/v#{version}/kubefwd_Darwin_x86_64.tar.gz"
      sha256 "f690dfcba6b5a9c13d9a773f8e5c4a4f376102f155b175ade5a4d85972066235"
    end
    on_arm do
      url "https://github.com/txn2/kubefwd/releases/download/v#{version}/kubefwd_Darwin_arm64.tar.gz"
      sha256 "15a80c3142c2c8e69cdc25c2a05766fe338cd8040104fca15ebf1f1432dada56"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/txn2/kubefwd/releases/download/v#{version}/kubefwd_Linux_x86_64.tar.gz"
      sha256 "2226532f1c5df185bb39caabea82530b955e7ccb56a117cddc11e7bd8e679cf9"
    end
    on_arm do
      url "https://github.com/txn2/kubefwd/releases/download/v#{version}/kubefwd_Linux_arm64.tar.gz"
      sha256 "cba01563e63c09624bf104a393d3ff45fd44b5368ab75dba05a1f3e83879056d"
    end
  end

  caveats do
    "kubefwd requires sudo to modify /etc/hosts and network interfaces."
  end

  # No zap stanza required
end
