# This file was generated by GoReleaser. DO NOT EDIT.
class Fxapi < Formula
  desc "Fake API server."
  homepage "https://github.com/txn2/fxapi"
  url "https://github.com/txn2/fxapi/releases/download/v1.1.1/fxapi_macOS_amd64.tar.gz"
  version "1.1.1"
  sha256 "c507ee6ab0f906884d22834280dbe0c8f6bbf1b66028095698cdfa9cbd2c4663"

  def install
    bin.install "fxapi"
  end

  test do
    fxapi -version
  end
end
