# This file was generated by GoReleaser. DO NOT EDIT.
class Kubefwd < Formula
  desc "Kubernetes bulk port forwarding utility."
  homepage "https://github.com/txn2/kubefwd"
  url "https://github.com/txn2/kubefwd/releases/download/v1.9.0/kubefwd_macOS_amd64.tar.gz"
  version "1.9.0"
  sha256 "a38831d1f0695b1ea62464c2b465e6e73c38ab132e424215cb57d2d731506ff3"

  def install
    bin.install "kubefwd"
  end

  test do
    kubefwd version
  end
end
