# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubefwd < Formula
  desc "Kubernetes bulk port forwarding utility."
  homepage "https://github.com/txn2/kubefwd"
  version "1.23.2"
  license "Apache-2.0"

  depends_on "kubectl" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/txn2/kubefwd/releases/download/v1.23.2/kubefwd_Darwin_x86_64.tar.gz"
      sha256 "d33e42e373527523605ba0e2961eca6173fd3af86e8a5e16c4e7280ab792fc1c"

      def install
        bin.install "kubefwd"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/txn2/kubefwd/releases/download/v1.23.2/kubefwd_Darwin_arm64.tar.gz"
      sha256 "1337b7c3661c7c451bd6ef3818d9b47f296619fd29681f0bf7743eb7d7fac160"

      def install
        bin.install "kubefwd"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/txn2/kubefwd/releases/download/v1.23.2/kubefwd_Linux_x86_64.tar.gz"
      sha256 "1268a5575acca3cfa053fc000247f4067f62481d3449462f054023f91738a8c0"
      def install
        bin.install "kubefwd"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/txn2/kubefwd/releases/download/v1.23.2/kubefwd_Linux_armv6.tar.gz"
      sha256 "868abefffaeb0057defdf032f2ae6f827198fda1028c2cfd09ab78817bc409bf"
      def install
        bin.install "kubefwd"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/txn2/kubefwd/releases/download/v1.23.2/kubefwd_Linux_arm64.tar.gz"
      sha256 "6d2502ff9e687f2e637c7940f2a29ce5d6e94c15cfae9a8cba1b7920a3cb1de9"
      def install
        bin.install "kubefwd"
      end
    end
  end

  test do
    system "#{bin}/kubefwd version"
  end
end
