# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class McpDataPlatform < Formula
  desc "Semantic data platform MCP server with bidirectional cross-injection"
  homepage "https://github.com/txn2/mcp-data-platform"
  version "0.1.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/txn2/mcp-data-platform/releases/download/v0.1.0/mcp-data-platform_0.1.0_darwin_amd64.tar.gz"
      sha256 "fefab5e1fba5d9d34f8e00fe8255728a4fc8ca2ee353e0d2e1a0228e6bc95333"

      def install
        bin.install "mcp-data-platform"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/txn2/mcp-data-platform/releases/download/v0.1.0/mcp-data-platform_0.1.0_darwin_arm64.tar.gz"
      sha256 "cb983a75b5acfd3b71555f96e290738c4726cf2245560621d98ccb1a53cf4365"

      def install
        bin.install "mcp-data-platform"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/txn2/mcp-data-platform/releases/download/v0.1.0/mcp-data-platform_0.1.0_linux_amd64.tar.gz"
      sha256 "8356c073bb18f299decd10d0bd1c6fdc500c8c81d96ba9c54b425ef5f997e659"
      def install
        bin.install "mcp-data-platform"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/txn2/mcp-data-platform/releases/download/v0.1.0/mcp-data-platform_0.1.0_linux_arm64.tar.gz"
      sha256 "19c9893b8c4203c40ee6ef2e149ca12f2f4b0205147b538fba9e787311fca25c"
      def install
        bin.install "mcp-data-platform"
      end
    end
  end

  test do
    system "#{bin}/mcp-data-platform", "--version"
  end
end
