# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class McpS3 < Formula
  desc "MCP server for Amazon S3 and S3-compatible storage"
  homepage "https://github.com/txn2/mcp-s3"
  version "0.1.3"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/txn2/mcp-s3/releases/download/v0.1.3/mcp-s3_0.1.3_darwin_amd64.tar.gz"
      sha256 "528900407c04c549301c4075853fe166b2e5a60a821bfdfb8d0fcd878b1a269f"

      def install
        bin.install "mcp-s3"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/txn2/mcp-s3/releases/download/v0.1.3/mcp-s3_0.1.3_darwin_arm64.tar.gz"
      sha256 "a6d407d1f6f51703963258a964f7c87f34b3a650ea6afe5bae86a203c7cfa5cd"

      def install
        bin.install "mcp-s3"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/txn2/mcp-s3/releases/download/v0.1.3/mcp-s3_0.1.3_linux_amd64.tar.gz"
      sha256 "46b765b1a787594bd750f534af7ea47f3a492be423ce6e2cf3ac079aff822c2f"
      def install
        bin.install "mcp-s3"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/txn2/mcp-s3/releases/download/v0.1.3/mcp-s3_0.1.3_linux_arm64.tar.gz"
      sha256 "1d15e897ac8975145b9d20f653af3132d9fcf2b508f3d80d6b036ed4131ebf0c"
      def install
        bin.install "mcp-s3"
      end
    end
  end

  test do
    system "#{bin}/mcp-s3", "--version"
  end
end
