# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class McpDataPlatform < Formula
  desc "Semantic data platform MCP server with bidirectional cross-injection"
  homepage "https://github.com/txn2/mcp-data-platform"
  version "0.28.4"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/txn2/mcp-data-platform/releases/download/v0.28.4/mcp-data-platform_0.28.4_darwin_amd64.tar.gz"
      sha256 "6c927559ae494f8cb66db1c2c2cc114bc699ce76b87bb5a9dc660598dc9df806"

      def install
        bin.install "mcp-data-platform"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/txn2/mcp-data-platform/releases/download/v0.28.4/mcp-data-platform_0.28.4_darwin_arm64.tar.gz"
      sha256 "ccdb83b0c529dae27c04e43c83fb25e0e516887bf610c8088da7da7226922c15"

      def install
        bin.install "mcp-data-platform"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/txn2/mcp-data-platform/releases/download/v0.28.4/mcp-data-platform_0.28.4_linux_amd64.tar.gz"
      sha256 "e7a881264b38f4df15f3ee6fa56271d82fb692adfdd50e23de9f9abea365d2d5"
      def install
        bin.install "mcp-data-platform"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/txn2/mcp-data-platform/releases/download/v0.28.4/mcp-data-platform_0.28.4_linux_arm64.tar.gz"
      sha256 "808b9063ab973ed8e6a5b071a99ed77474e89a9350dd2f68a2fd397d8060b590"
      def install
        bin.install "mcp-data-platform"
      end
    end
  end

  test do
    system "#{bin}/mcp-data-platform", "--version"
  end
end
