# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class McpTrino < Formula
  desc "MCP server for Trino data warehouses"
  homepage "https://github.com/txn2/mcp-trino"
  version "1.6.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/txn2/mcp-trino/releases/download/v1.6.0/mcp-trino_1.6.0_darwin_amd64.tar.gz"
      sha256 "2d2a7c55edd2a17c843343f45c24230c8581da2478c6dbb6d4369e0864034707"

      def install
        bin.install "mcp-trino"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/txn2/mcp-trino/releases/download/v1.6.0/mcp-trino_1.6.0_darwin_arm64.tar.gz"
      sha256 "6936df00154cc3a98c47887d7195833aed8bc2fa38c87ba03d1e484df7baf192"

      def install
        bin.install "mcp-trino"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/txn2/mcp-trino/releases/download/v1.6.0/mcp-trino_1.6.0_linux_amd64.tar.gz"
      sha256 "69b2a312961eb7d7394e00cd9af79792e6535c727083ea72de39e7959086af8b"
      def install
        bin.install "mcp-trino"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/txn2/mcp-trino/releases/download/v1.6.0/mcp-trino_1.6.0_linux_arm64.tar.gz"
      sha256 "c3b91bc75a4a56249c786b5e1511cad9d0f1c456982c4a7f73e15ec62a2ceb50"
      def install
        bin.install "mcp-trino"
      end
    end
  end

  test do
    system "#{bin}/mcp-trino", "--version"
  end
end
