# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class McpDatahub < Formula
  desc "MCP server for DataHub data catalogs"
  homepage "https://github.com/txn2/mcp-datahub"
  version "0.2.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/txn2/mcp-datahub/releases/download/v0.2.0/mcp-datahub_0.2.0_darwin_amd64.tar.gz"
      sha256 "a8db66d1973cf2511b82e64338911776c9f88e4cdcae129dad4abd8d19d12f41"

      def install
        bin.install "mcp-datahub"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/txn2/mcp-datahub/releases/download/v0.2.0/mcp-datahub_0.2.0_darwin_arm64.tar.gz"
      sha256 "798108a7c85639f77dffefcaffac0b04223f858af0fd11c6da2bd0839b925823"

      def install
        bin.install "mcp-datahub"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/txn2/mcp-datahub/releases/download/v0.2.0/mcp-datahub_0.2.0_linux_amd64.tar.gz"
      sha256 "87f41f450242aa35ae103319503e7d2fa2e142decea9b2634b9a7a9f314b3b93"
      def install
        bin.install "mcp-datahub"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/txn2/mcp-datahub/releases/download/v0.2.0/mcp-datahub_0.2.0_linux_arm64.tar.gz"
      sha256 "4d20644a507a5730bcbb7574086ee7a5df83c176f1ea3ac161eb94506ff73c0f"
      def install
        bin.install "mcp-datahub"
      end
    end
  end

  test do
    system "#{bin}/mcp-datahub", "--version"
  end
end
