# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class McpTrino < Formula
  desc "MCP server for Trino data warehouses"
  homepage "https://github.com/txn2/mcp-trino"
  version "0.6.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/txn2/mcp-trino/releases/download/v0.6.1/mcp-trino_0.6.1_darwin_amd64.tar.gz"
      sha256 "b8605e90c65872317eb838747e8471c7eb1b3d0b065f353620bf0aff622b860b"

      def install
        bin.install "mcp-trino"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/txn2/mcp-trino/releases/download/v0.6.1/mcp-trino_0.6.1_darwin_arm64.tar.gz"
      sha256 "d5b8867ac13ae832cc06f74248fa9ac88b26531c9d54d89ecc2df846ea30e885"

      def install
        bin.install "mcp-trino"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/txn2/mcp-trino/releases/download/v0.6.1/mcp-trino_0.6.1_linux_amd64.tar.gz"
      sha256 "c634db4040ff04dbed5f4d6782d50ebc83b4116554feb75ee1133e284e363846"
      def install
        bin.install "mcp-trino"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/txn2/mcp-trino/releases/download/v0.6.1/mcp-trino_0.6.1_linux_arm64.tar.gz"
      sha256 "e011c15b0d669f07d46f14397297eb122223b7a2d08e00d17460849e5d8b1522"
      def install
        bin.install "mcp-trino"
      end
    end
  end

  test do
    system "#{bin}/mcp-trino", "--version"
  end
end
