# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class McpDatahub < Formula
  desc "MCP server for DataHub data catalogs"
  homepage "https://github.com/txn2/mcp-datahub"
  version "1.10.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/txn2/mcp-datahub/releases/download/v1.10.0/mcp-datahub_1.10.0_darwin_amd64.tar.gz"
      sha256 "981fa98e704bd5f8457769fab617dfaca77b60d8ad9891ccbe26b138a70e264f"

      def install
        bin.install "mcp-datahub"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/txn2/mcp-datahub/releases/download/v1.10.0/mcp-datahub_1.10.0_darwin_arm64.tar.gz"
      sha256 "204729664b7fc027ed99b9895dd95b2af8a1f0637574a7d87be448002d3aaf83"

      def install
        bin.install "mcp-datahub"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/txn2/mcp-datahub/releases/download/v1.10.0/mcp-datahub_1.10.0_linux_amd64.tar.gz"
      sha256 "e0e90980c6def78a9851c2d6e6aab59ec290633d82c71a56e88393193f4d21f5"
      def install
        bin.install "mcp-datahub"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/txn2/mcp-datahub/releases/download/v1.10.0/mcp-datahub_1.10.0_linux_arm64.tar.gz"
      sha256 "76b68ffb8ad0d4628321c1b49cc7e18aa5cde56ee5f12550b3a89c3c2fab92f0"
      def install
        bin.install "mcp-datahub"
      end
    end
  end

  test do
    system "#{bin}/mcp-datahub", "--version"
  end
end
