# This file was generated by GoReleaser. DO NOT EDIT.
class P3y < Formula
  desc "Mini reverse proxy with Basic Auth and TLS support."
  homepage "https://github.com/txn2/p3y"
  url "https://github.com/txn2/p3y/releases/download/0.0.3/p3y_macOS_amd64.tar.gz"
  version "0.0.3"
  sha256 "830cda3169c122d224a2da04379802a0bde166526f22a5b2ad4e4a3f156702b3"

  def install
    bin.install "p3y"
  end

  test do
    kubefwd version
  end
end
