# This file was generated by GoReleaser. DO NOT EDIT.
class P3y < Formula
  desc "Mini reverse proxy with Basic Auth and TLS support."
  homepage "https://github.com/txn2/p3y"
  url "https://github.com/txn2/p3y/releases/download/1.0.0/p3y_macOS_amd64.tar.gz"
  version "1.0.0"
  sha256 "44dac131ef6843a6dac67dd9a7230ced4de1a9a8e0233b59eb324ce05ed0271f"

  def install
    bin.install "p3y"
  end

  test do
    kubefwd version
  end
end
