# This file was generated by GoReleaser. DO NOT EDIT.
class Pvctl < Formula
  desc "Provision CLI."
  homepage "https://github.com/txn2/pvctl"
  url "https://github.com/txn2/pvctl/releases/download/v0.0.2/pvctl_macOS_amd64.tar.gz"
  version "0.0.2"
  sha256 "cdbfe09ee1695b30d7ee2fa7f3baca796562699e5464f7b2e1e976ea23982ba8"

  def install
    bin.install "pvctl"
  end
end
