# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rtbeat < Formula
  desc "Elastic Beat that receives rxtx batches over HTTP and publishes them as Beats events."
  homepage "https://github.com/txn2/rtbeat"
  version "1.2.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/txn2/rtbeat/releases/download/v1.2.1/rtbeat_Darwin_x86_64.tar.gz"
      sha256 "5631e21a52226172f8cdaca99edb63237429aa2cb829a5aa6c8d8e09d2434748"

      def install
        bin.install "rtbeat"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/txn2/rtbeat/releases/download/v1.2.1/rtbeat_Darwin_arm64.tar.gz"
      sha256 "470581558f18d5cfd0902507b6427bc20628ac968e6ab0f4bc9c62b9ac8ccf52"

      def install
        bin.install "rtbeat"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/txn2/rtbeat/releases/download/v1.2.1/rtbeat_Linux_x86_64.tar.gz"
      sha256 "95709c3417db854d7bb7eadad92acfa994a2d7c3f5559b7d89f47a7ee0e09f54"
      def install
        bin.install "rtbeat"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/txn2/rtbeat/releases/download/v1.2.1/rtbeat_Linux_arm64.tar.gz"
      sha256 "8bf3959a34b3ad0acc00e4c38f06a4899d369782d058987a0ede3d1d02155d60"
      def install
        bin.install "rtbeat"
      end
    end
  end

  test do
    system "#{bin}/rtbeat version"
  end
end
