# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Rxtx < Formula
  desc "Data queuing, batching and re-transmission."
  homepage "https://github.com/txn2/rxtx"
  version "2.0.5"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/txn2/rxtx/releases/download/v2.0.5/rxtx_Darwin_x86_64.tar.gz"
      sha256 "12be3f650e2b01ab2ecb3c468ee645f2deb4c2a0d9aa160bf1f9cb4a2b24a1f4"
    end
    if Hardware::CPU.arm?
      url "https://github.com/txn2/rxtx/releases/download/v2.0.5/rxtx_Darwin_arm64.tar.gz"
      sha256 "4a96c9d088d2d52b08abd343c39833366427d9985ec53732a83e33f820317b67"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/txn2/rxtx/releases/download/v2.0.5/rxtx_Linux_x86_64.tar.gz"
      sha256 "abfad7b9554280f9f8a6598eb063b0ba84871f001a1ed6ce4cd4f59597560e35"
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/txn2/rxtx/releases/download/v2.0.5/rxtx_Linux_armv6.tar.gz"
      sha256 "60cd625fc91e507398b81c714461c40fb1629a8fae63191e0ce7e085cfebc774"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/txn2/rxtx/releases/download/v2.0.5/rxtx_Linux_arm64.tar.gz"
      sha256 "ea4179a884a9a9e989dfbc1845e60748f7d60cfe8883039649c7dd8261911380"
    end
  end

  def install
    bin.install "rxtx"
  end
end
