# This file was generated by GoReleaser. DO NOT EDIT.
class Rxtx < Formula
  desc "Data queuing, batching and re-transmission."
  homepage "https://github.com/txn2/rxtx"
  url "https://github.com/txn2/rxtx/releases/download/v2.0.1/rxtx_darwin_amd64.tar.gz"
  version "2.0.1"
  sha256 "bf50825e718b0eba208410ef108fd29ed118ed6cc402659e0d5e66e43c55d156"

  def install
    bin.install "rxtx"
  end
end
