# This file was generated by GoReleaser. DO NOT EDIT.
class Txnject < Formula
  desc "txnject"
  homepage "https://github.com/txn2/txnject"
  url "https://github.com/txn2/txnject/releases/download/v0.0.1/txnject_0.0.1_darwin_amd64.tar.gz"
  version "0.0.1"
  sha256 "59150d86d8c33525b9a30e264063390f9abadcde548d050e9574ce446ee022bf"

  def install
    bin.install "txnject"
  end
end
